version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zalex_invoicing
      POSTGRES_USER: zalex_user
      POSTGRES_PASSWORD: zalex_password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  invoicing:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zalex_invoicing
      SPRING_DATASOURCE_USERNAME: zalex_user
      SPRING_DATASOURCE_PASSWORD: zalex_password
    depends_on:
      - postgres
